<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2023" os="Windows 10" host="DINM5CD140FS86"><DocLocation><![CDATA[C:\Users\z004u4nm\Documents\UFT One\login]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[login]]></DName>
<Res><![CDATA[login]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[AWC_end _to_end]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[05-10-2023 - 12:24:49]]></Time>
<TimeTick>1696488889</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Details>
<Time><![CDATA[05-10-2023 - 12:24:49]]></Time>
<TimeTick>1696488889</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[Run "chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[BT StartUpManager]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:09]]></Time>
<TimeTick>1696488909</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["BT StartUpManager"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (19 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (19 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=BT StartUpManager 2023-09-04 11:06<SPAN class=Failed> (Skipped)</SPAN><br>title=BT StartUpManager 2023-09-04 11:06<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://gplm.automation.siemens.com/globalconf/sm/sm2.html?version=cat&project=bt<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>opentitle=IEC StartUpManager 2023-09-04 11:06<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=5<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:09]]></Time>
<TimeTick>1696488909</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA["BT StartUpManager"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[BT StartUpManager.Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:09]]></Time>
<TimeTick>1696488909</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[BT StartUpManager.Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[BT StartUpManager.ClearCache]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:10]]></Time>
<TimeTick>1696488910</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[BT StartUpManager.ClearCache]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[BT StartUpManager]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:12]]></Time>
<TimeTick>1696488912</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[AWC__BT_text.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:12]]></Time>
<TimeTick>1696488912</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[AWC__BT_text.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[AWC__BT__Q.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:14]]></Time>
<TimeTick>1696488914</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[AWC__BT__Q.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[AWC__BT__Q.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:16]]></Time>
<TimeTick>1696488916</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[AWC__BT__Q.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[server_ID_dropdown.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["MyTC R2.2 QA (TCBQ10) TC 13.2"]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:19]]></Time>
<TimeTick>1696488919</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[server_ID_dropdown.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Start AWC.Submit]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:21]]></Time>
<TimeTick>1696488921</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="27" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[Start AWC.Submit]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="18" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[BT StartUpManager]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[BT StartUpManager]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Environment Selection]]></Obj>
<Details ><![CDATA[TCBQ10 selected successfully]]></Details>
<Time><![CDATA[05-10-2023 - 12:25:21]]></Time>
<TimeTick>1696488921</TimeTick>
<NodeArgs eType="User" icon="12" nRep="28" status="Passed" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[Environment Selection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Teamcenter - Home]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["Teamcenter - Home"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (20 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (20 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Teamcenter - Home<SPAN class=Failed> (Skipped)</SPAN><br>title=Teamcenter - Home<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://tcbqlb.gplm.siemens.com/tcbq10awc/?locale=en_US<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>opentitle=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=2<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA["Teamcenter - Home"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[signinstage.siemens.com/regpub]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[LoginButton.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[LoginButton.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[login_time]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "login_time" started.]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<NodeArgs eType="Transaction" icon="13" nRep="33" nType="Start Transaction" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[login_time]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[LoginButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="35" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[LoginButton.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="31" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[signinstage.siemens.com/regpub]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="29" Source="AWC_end _to_end" SourceLine="-1" >
<Disp><![CDATA[Teamcenter - Home]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Failed to run the test due to an unknown error.<BR/>Line (77): &quot;UIAProPane(&quot;pkisigninstage.siemens.com&quot;).InsightObject(&quot;Certificate_OK&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:07]]></Time>
<TimeTick>1696489027</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="36" status="Failed" Source="AWC_end _to_end" SourceLine="76" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:27]]></Time>
<TimeTick>1696489047</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Windows&nbsp;Security"&nbsp;(of&nbsp;class&nbsp;UIAWindow).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:27]]></Time>
<TimeTick>1696489047</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>supportedpatterns = Window;Transform<br>path = *:*<br>Name = Windows Security<br>frameworkid = XAML<br>controltype = Window<br>]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:27]]></Time>
<TimeTick>1696489047</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="41" status="Failed" nType="Description" Source="AWC_end _to_end" SourceLine="76" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="15" nRep="40" status="Failed" nType="Run Error" Source="AWC_end _to_end" SourceLine="76" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="39" status="Failed" Source="AWC_end _to_end" SourceLine="76" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:27]]></Time>
<TimeTick>1696489047</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Windows Security&quot; (of class UIAWindow).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (80): &quot;UIAWindow(&quot;Windows Security&quot;).Activate&quot;. ]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:27]]></Time>
<TimeTick>1696489047</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="43" status="Failed" Source="AWC_end _to_end" SourceLine="79" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[PIN]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAEdit]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:32]]></Time>
<TimeTick>1696489052</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[PKI_PIN]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"PKI_PIN"&nbsp;object's&nbsp;parent&nbsp;"Windows&nbsp;Security"&nbsp;(class&nbsp;UIAWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:32]]></Time>
<TimeTick>1696489052</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>supportedpatterns = Window;Transform<br>path = *:*<br>Name = Windows Security<br>frameworkid = XAML<br>controltype = Window<br>]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:32]]></Time>
<TimeTick>1696489052</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="48" status="Failed" nType="Parent description" Source="AWC_end _to_end" SourceLine="79" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="16" nRep="47" status="Failed" nType="Run Error" Source="AWC_end _to_end" SourceLine="79" >
<Disp><![CDATA[PKI_PIN]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[05-10-2023 - 12:27:32]]></Time>
<TimeTick>1696489052</TimeTick>
<NodeArgs eType="General" icon="17" nRep="49" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="16" nRep="46" status="Failed" Source="AWC_end _to_end" SourceLine="79" >
<Disp><![CDATA[PIN]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="42" status="Failed" Source="AWC_end _to_end" SourceLine="79" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="05-10-2023 - 12:24:48" eTime="05-10-2023 - 12:27:32" passed="2" failed="6" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[AWC_end _to_end Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="05-10-2023 - 12:24:30" eTime="05-10-2023 - 12:27:32" passed="2" failed="6" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>